services:
  - type: web
    name: book-store-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: mongodb
          property: connectionString
    plan: free
    region: singapore  # Choose the region closest to your users
